### ISSUE TITLE
Compute hashes of compressed file and store in meta-data

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/mtscomp#4]
There has been some local copy issues lately, and it became difficult to know if the problem came from a) an corruption of the uncompressed file, b) a compression issue, c) a corruption of the compressed file.

Spikeglx stores the SHA1 hash of the binary file, so we were able to show the issues came from a corruption of the uncompressed file, but it would be useful to add a hash in the metadata file to assert the integrity of the compressed file if needed.

About implementation, an option could be using `hashlib.sha1().update()` as it allows to do this online without incurring any I/O.

**Comment by rossant** [comment]
done
