### ISSUE TITLE
compression ratio decreases with file size

### ISSUE THREAD

**Issue by LaurenzMuessig** [int-brain-lab/mtscomp#9]
Hi,

I noticed in my data that the compression ratio decreases a lot with increasing file size. While I get ~2.5x compression with a 20ish GB file, I only achieve ~1.4x with a 350GB file. Is that to be expected or can I tweak the parameters to achieve a better rate of compression? Thanks for your help.
PS: For context: I am using Neuropixel 1.0 and I spike sort a whole session by concatenating all data from it (using KS3). Then, I want to compress the drift corrected file that kilosort generates.

Any help is appreciated. 

Cheers

Laurenz

**Comment by rossant** [comment]
I guess you could try to increase the chunk duration but I'd be a bit surprised if that changed much the compression ratio.

Something else to keep is mind is that, if the file you compress has been manually edited, you should double-check that the number of channels is correct. If it's not, you might *not* get an error, but the per-channel temporal differences are going to be uncorrelated which would significantly impact the compression ratio.

**Comment by LaurenzMuessig** [comment]
Hi Cyrille,
Thanks for your quick response. I had already tried using a chunk size of 10s and as you said, there wasn't any difference. And yes, I pass the actual number of channels as an input. Btw, I am doing this on a linux machine. Could that be the issue?  
Thanks for your help

**Comment by rossant** [comment]
I don't think Linux is the issue as this is what I also use.
I fear there might not be a lot of further things to try out. It may just be that the compression ratio is suboptimal on certain datasets.

**Comment by LaurenzMuessig** [comment]
Okay. Thanks for your help Cyrille. If I find the issue I'll post it here.
Cheers
